AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  DisplayCopNames: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Max: 80

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  CountComments: false
  Max: 120

Metrics/PerceivedComplexity:
  Max: 20
